### ISSUE TITLE
Deploy this repo

### ISSUE THREAD

**Issue by martin-henz** [source-academy/general#3]
Can we generate something like this
https://nus-plse.github.io/
from the READMEs and deploy it as
https://source-academy.github.io/about
?

**Comment by martin-henz** [comment]
We could reuse some of the infrastructure of the new sicp section of the frontend. @samuelfangjw

**Comment by martin-henz** [comment]
Btw, this page https://nus-plse.github.io/
was made by @Gopiandcode .

**Comment by samuelfangjw** [comment]
> We could reuse some of the infrastructure of the new sicp section of the frontend. @samuelfangjw

That would be possible. Alternatively, I think it might be easier to deploy it using [GitHub Pages](https://pages.github.com), similar to how we deploy SICP, then add links to it on the cadet frontend if needed.

I tried forking this repo and deploying on my own domain at [http://www.samuelfangjw.com/general/](http://www.samuelfangjw.com/general/). I propose we do something similar and then add some custom styles to make it look good.

**Comment by chownces** [comment]
Hi, just saw this. We could use a site generator like mkdocs since we already have all the content as markdown files. Something like: https://nus-cs2030s.github.io/2021-s2/index.html

The CI for deployment to GitHub pages is also easy to setup

The theme used by the CS2030S team: https://squidfunk.github.io/mkdocs-material/getting-started/
